# NumPy Basics

In [1]:
import numpy as np

***
## Creating arrays

In [2]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], dtype = float)
c = np.array([[1, 6], [2, 7], [3, 8], [4, 9], [5, 10]], dtype = int)

In [4]:
print a
print b
print c

[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [19]:
np.arange?

In [20]:
np.arange(0, 10, 2)     # array of evenly spaced values

array([0, 2, 4, 6, 8])

In [21]:
np.zeros?

In [6]:
np.zeros((2, 3))     # array of zeros with the given shape

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones?

In [33]:
d = np.ones((5,6))           # array of ones with the given shape

In [40]:
e = np.full((5,6),2)

In [34]:
print d

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [35]:
d.size

30

In [36]:
d.ndim

2

In [37]:
d.shape

(5, 6)

In [38]:
d.dtype

dtype('float64')

In [29]:
np.empty?

In [27]:
np.empty((2, 3))     # empty array (arbitrary values)

array([[3.10503618e+231, 3.10503618e+231, 2.21411429e-314],
       [2.29198067e-314, 0.00000000e+000, 4.17201348e-309]])

In [28]:
np.full?

In [12]:
np.full((6, 8), 4)   # fill new array with given shape

array([[4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4]])

***
## Inspecting an array

In [30]:
b.size               # number of elements in the array

10

In [9]:
b.ndim               # number of dimensions

2

In [10]:
b.shape              # lengths of each dimension

(2, 5)

In [11]:
b.dtype              # data type of array elements

dtype('float64')

***
## Basic operations

### Element-wise arithmetic

In [39]:
b + c                # element-wise addition (or np.add)

ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 

In [41]:
print d + e

[[3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]]


In [ ]:
b - c                # element-wise subtraction (or np.subtract)

In [ ]:
b * c                # element-wise multiplication (or np.multiply)

In [ ]:
b / c                # element-wise division (or np.divide)

### Aggregation

In [ ]:
b.sum()              # sum elements

In [42]:
d.sum()

30.0

In [45]:
b.min()              # minimum element

0.0

In [43]:
b.max()              # maximum element

9.0

In [44]:
b.mean()             # mean of elements

4.5

### Element-wise comparison

In [46]:
a == a               # element-wise comparison

array([ True,  True,  True,  True,  True])

In [49]:
b < 2                # element-wise comparison

array([[ True,  True, False, False, False],
       [False, False, False, False, False]])

In [48]:
d == e

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

### Array-level equality

In [ ]:
np.array_equal(a, b)  # check whether arrays have the same shape and elements

***
## Linear algebra

In [87]:
h = b.T                    # reverse the array dimensions (or np.transpose)

In [88]:
b

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [89]:
h

array([[0., 5.],
       [1., 6.],
       [2., 7.],
       [3., 8.],
       [4., 9.]])

In [80]:
f = np.array([4,3,2,1,0])

In [81]:
a.dot(f)               # dot product (or np.dot)

10

In [82]:
b @ c                  # matrix multiplication (or np.matmul)

SyntaxError: invalid syntax (<ipython-input-82-c7c0ed340349>, line 1)

In [ ]:
x = c.T @ c
np.linalg.inv(x)       # matrix inverse

In [ ]:
b.trace()              # trace of a matrix

In [ ]:
np.eye(3)              # identity matrix

***
## Universal functions (ufuncs)

In [51]:
np.exp(a)              # exponential function

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [52]:
np.sin(a)              # sine function

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [53]:
np.log(c)              # natural logarithm

array([[0.        , 1.79175947],
       [0.69314718, 1.94591015],
       [1.09861229, 2.07944154],
       [1.38629436, 2.19722458],
       [1.60943791, 2.30258509]])

In [54]:
np.abs(-b)              # absolute value

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [50]:
np.power(b, 3)          # raise to a power

array([[  0.,   1.,   8.,  27.,  64.],
       [125., 216., 343., 512., 729.]])

***
## Copying arrays

In [56]:
aa = a.copy()          # make a deep copy of the array
aa.fill(6)
print(a)
print(aa)

[0 1 2 3 4]
[6 6 6 6 6]


In [57]:
aaa = aa.view()          # create a view of the array (points to the same data in memory)
aaa.fill(1)
print(aa)
print(aaa)

[1 1 1 1 1]
[1 1 1 1 1]


***
## Array manipulation

In [58]:
b.ravel()              # flatten the array (or np.ravel)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [59]:
np.ravel(b)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [60]:
b.reshape(5,2)         # change shape, but don't change values

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [61]:
np.resize(b, (6,2))    # create a new array with a different shape

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.],
       [0., 1.]])

In [62]:
np.append(a, [1, 1])   # append values to the end of an array

array([0, 1, 2, 3, 4, 1, 1])

In [63]:
np.insert(a, 2, [1, 1]) # insert values at a given location

array([0, 1, 1, 1, 2, 3, 4])

In [64]:
np.delete(a, [0,2])    # delete elements at given locations

array([1, 3, 4])

In [68]:
b + 10

array([[10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [67]:
np.concatenate((b, b+10), axis = 0)  # concatenate arrays

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [69]:
np.r_[b, b + 10]        # shorthand: concatenate arrays along their first axis (row-wise)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [70]:
np.c_[b, b + 10]        # shorthand: concatenate arrays along their second axis (column-wise)

array([[ 0.,  1.,  2.,  3.,  4., 10., 11., 12., 13., 14.],
       [ 5.,  6.,  7.,  8.,  9., 15., 16., 17., 18., 19.]])

In [71]:
np.split(b, 2, axis = 0) # split an array into sub-arrays

[array([[0., 1., 2., 3., 4.]]), array([[5., 6., 7., 8., 9.]])]

***
## Indexing/slicing

In [72]:
b[0,1]                     # select a single element (at row 0, column 1)

1.0

In [73]:
a[0:4]                     # select a slice

array([0, 1, 2, 3])

In [74]:
a[0:4:2]                   # select a slice with a stride

array([0, 2])

In [83]:
g = a[::-1]                    # select all elements in reverse

In [84]:
a

array([0, 1, 2, 3, 4])

In [85]:
g

array([4, 3, 2, 1, 0])

In [76]:
b[:,2]                     # select all elements along the first axis (all rows) and only the elements with index 2 along the second axis

array([2., 7.])

In [77]:
a[:, np.newaxis]           # insert a new axis (here: convert a 1D array to a column vector)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [78]:
a[a>2]                     # boolean indexing

array([3, 4])